version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  checkWebStatus:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Check for status 200."
          command: |
            webService=$(curl -o /dev/null -s -w "%{http_code}\n" https://www.zxvczxfdsfatvapijkipjmmvads.com)
            if [ $webService -eq 200 ]; 
            then  cp .circleci/webserviceOkConfig.yml .circleci/nextConfig.yml
            fi
            cat .circleci/nextConfig.yml
      - continuation/continue:
          configuration_path: .circleci/nextConfig.yml
workflows:
  checkWebStatus:
    jobs:
      - checkWebStatus
